version: '1'
services:
  dev:
    command: "python3 app.py"
    image: rachelt2/st123798-mlassignment2:latest
    environment:
      - HOST=0.0.0.0
      - PORT=80
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st123798.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is web-st123783
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st123798.rule=Host(`st123798.ml2024.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st123798.tls=true
      - traefik.http.routers.web-st123798.tls.certresolver=production
      - traefik.http.routers.web-st123798.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true